title = "Encavernados"
theme = "doit"
languageCode = "es-ar"
baseURL = "https://encavernados.com/"

defaultContentLanguage = "es"

pagination.pagerSize = "3"

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "static/media"
    target = "assets/media"

[params]
  mainSections = ["articulos"]
  CSS = ["css/custom.css"]
  defaultCover = "/media/default-cover.webp"
  defaultTheme = "auto"
  description = "Encavernados es un grupo de reflexión filosófica argentina que comparte artículos, libros y recursos comunitarios."
  keywords = ["Encavernados", "filosofía argentina", "pensamiento nacional", "reflexión filosófica"]
  images = ["/media/portada.webp"]

[params.header]
  themeChangeMode = "switch"

[permalinks]
  articulos = "/articulos/:slug/"

[menu]
  [[menu.main]]
    identifier = "inicio"
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "articulos"
    name = "Artículos"
    url = "/articulos/"
    weight = 2

  [[menu.main]]
    identifier = "entrevistas"
    name = "Entrevistas"
    url = "/entrevistas/"
    weight = 3

  [[menu.main]]
    identifier = "reflexiones"
    name = "Reflexiones"
    url = "/reflexiones/"
    weight = 4

  [[menu.main]]
    identifier = "libros"
    name = "Libros"
    url = "/libros/"
    weight = 5

  [[menu.main]]
    identifier = "sobre"
    name = "Sobre nosotros"
    url = "/sobre/"
    weight = 6

  [[menu.main]]
    identifier = "contacto"
    name = "Contacto"
    url = "/contact/"
    weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[outputs]
  home    = ["HTML", "RSS"]
  section = ["HTML", "JSON"]

[mediaTypes."application/json"]
  suffixes = ["json"]

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true
  notAlternative = true

[params.social]
  instagram = "https://www.instagram.com/encavernados_filosofia"
  youtube = "https://www.youtube.com/@Encavernados"
  email = "mailto:encavernados@gmail.com"
