title = "Encavernados"
theme = "doit"
languageCode = "es-ar"
baseURL = "https://encavernados.com/"

defaultContentLanguage = "es"

pagination.pagerSize = "3"

# La sección principal (el “blog”) será /articulos

[params]
  mainSections = ["articulos"]
 CSS = ["css/custom.css"]
   defaultCover = "/media/default-cover.webp"

# URLs prolijas para artículos
[permalinks]
  articulos = "/articulos/:slug/"




# Menú principal
[menu]
  [[menu.main]]
    identifier = "inicio"
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "articulos"
    name = "Artículos"
    url = "/articulos/"
    weight = 2

  [[menu.main]]
    identifier = "categorias"
    name = "Categorías"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    identifier = "etiquetas"
    name = "Etiquetas"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "libros"
    name = "Libros"
    url = "/libros/"
    weight = 5

  [[menu.main]]
    identifier = "sobre"
    name = "Sobre nosotros"
    url = "/sobre/"
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[outputs]
  section = ["HTML", "JSON"]

[mediaTypes."application/json"]
  suffixes = ["json"]

[outputFormats.JSON]
  mediaType    = "application/json"
  baseName     = "index"
  isPlainText  = true
  notAlternative = true