backend:
  name: git-gateway
  branch: main

media_folder: "static/media"
public_folder: "/media"

locale: "es"
# Para publicar directo, comentá la línea de abajo:
# publish_mode: editorial_workflow

collections:
  - name: "articulos"
    label: "Artículos y Entrevistas"
    folder: "content/articulos"
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Autores", name: "authors", widget: "list", hint: "Elegí o agregá un autor"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Categoría", name: "categories", widget: "select", options: ["articulos", "entrevistas"]}
      - {label: "Imagen de portada", name: "cover", widget: "image", required: false}
-     - { label: "Video YouTube (ID o URL)", name: "youtube", widget: "string", required: false, hint: "Pegá el ID (p.ej: ki_E97HIN9A) o la URL completa" }
      - {label: "Descripción", name: "description", widget: "text", hint: "Resumen corto (máx 160 caracteres)"}
      - {label: "Cuerpo", name: "body", widget: "markdown"}


      
