backend:
  name: git-gateway
  branch: main

media_folder: "static/media"
public_folder: "/media"

locale: "es"
# Para publicar directo, comentá la línea de abajo:
# publish_mode: editorial_workflow

collections:
  - name: "articulos"
    label: "Artículos"
    label_singular: "Artículo"
    folder: "content/articulos"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"  # crea leaf bundle: content/articulos/slug/index.md
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "Borrador", name: "draft", widget: "boolean", default: false }
      - { label: "Categorías", name: "categories", widget: "list", default: [] }
      - { label: "Etiquetas", name: "tags", widget: "list", default: [] }
      - label: "Portada"
        name: "cover"
        widget: "image"
        allow_multiple: false
        hint: "Imagen de portada del artículo (se recomienda WebP)."
      - { label: "Descripción (resumen)", name: "description", widget: "text", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }